services:
  app:
    container_name: infinite-memes
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${HOST_PORT}:${PORT-80}"
    restart: unless-stopped